### ISSUE TITLE
Can't see images on readme

### ISSUE THREAD

**Issue by mukeshthawani** [tursunovic/xcode-themes#13]
<img width="609" alt="screen shot 2016-10-12 at 11 05 37 am" src="https://cloud.githubusercontent.com/assets/5956714/19298454/62552e9a-906b-11e6-8323-3a17de08fb54.png">
And when clicking on it, i get this
<img width="223" alt="screen shot 2016-10-12 at 11 04 45 am" src="https://cloud.githubusercontent.com/assets/5956714/19298467/774e76a8-906b-11e6-89d3-47f278a47d58.png">

**Comment by tursunovic** [comment]
@mukeshthawani it seems to work, can you confirm it?

**Comment by mukeshthawani** [comment]
Yeah, now it's working. Thanks

**Comment by RITL** [comment]
Sorry, this issue seems to have happened again..
